#!/bin/sh

# source xresources file
xrdb -merge /home/ashraf/.config/x11/xresources

# hotkey daemon
sxhkd &

# change the default cross cursor to left pointer cursor
xsetroot -cursor_name left_ptr &

# hide mouse cursor while not using it
xbanish &

# set both english and arabic layout
setxkbmap -layout us,ara -option grp:lalt_lshift_toggle &

# launch slstatus for dwm
slstatus &

# speed up keyboard
xset r rate 280 40 &

# start dunst notification server
dunst &

# launch picom compositor
picom &

# xmodmap ~/.Xmodmap &
# setup screen rate
# xrandr --verbose --output DisplayPort-2 --mode 1920x1080 --rate 144 &

# openrgb
[ "$(command -v openrgb)" ] && openrgb --profile default.orp &

# set last background
~/.config/setbg &
