#!/bin/sh

# source xresources file
xrdb \
  -I"${XDG_CONFIG_HOME}/x11" -I"${XDG_CONFIG_HOME}/ricing" -I"${HOME}/.local/src"  \
  -merge "$XDG_CONFIG_HOME/x11/xresources"

# hotkey daemon
sxhkd &

# change the default cross cursor to left pointer cursor
xsetroot -cursor_name left_ptr &

# hide mouse cursor while not using it
xbanish &

# set both english and arabic layout
setxkbmap -layout us,ara -option grp:lalt_lshift_toggle &

# launch slstatus for dwm
slstatus &

# speed up keyboard
xset r rate 300 30 &

# start dunst notification server
start-dunst &

# launch picom compositor
picom &

# setup screen rate
xrandr --verbose --output DisplayPort-2 --mode 1920x1080 --rate 144 &

# openrgb
[ "$(command -v openrgb)" ] && openrgb --profile default_red.orp &

# set last background
~/.config/setbg &
