#!/usr/bin/env bash

if [[ $1 -eq 'list' ]] && [[ -z $QUTE_COUNT ]]; then
  port="$(
    ss -nltp | tail -n +2 |
      awk '{print $4}' | awk -F: '{print $2}' | sed '/^\s*$/d' |
      fzf-menu
  )"
fi

[ -z "${port}" ] && exit

echo open -t localhost:"${port:-8080}" >"$QUTE_FIFO"
