#!/usr/bin/env node
//
// # Description
//
// Summarize the current page in a new tab, by processing it with the standalone readability
// library used for Firefox Reader View.
//
// # Prerequisites
//
// - Mozilla's readability library (npm install -g @mozilla/readability)
//     - Also available in the AUR as nodejs-readability-git
// - jsdom (npm install -g jsdom)
// - qutejs (npm install -g qutejs)
//
// - Ensure that node knows where to find your globally installed modules by adding
//   the following to ~/.profile or /etc/profile:
//     
//   export NODE_PATH=$NODE_PATH:$(npm root -g)
//
// *Note*: On some Linux distros and macOS, it may be easier to set NODE_PATH using qutebrowser's
// qt.environ setting. For instance, if 'npm root -g' returns /usr/lib/node_modules, then run:
//
//   :set qt.environ '{"NODE_PATH": "/usr/lib/node_modules"}'
//
// # Usage
//
// :spawn --userscript readability-js
//
// One may wish to define an easy to type command alias in qutebrowser's configuration file:
// c.aliases = {"readability" : "spawn --userscript readability-js", ...}

const { Readability } = require('@mozilla/readability');
const qute = require('qutejs');
const JSDOM = require('jsdom').JSDOM;
const fs = require('node:fs');
const path = require('node:path');
const util = require('node:util');

const HEADER = `
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <title>%s</title>
    <style type="text/css">
      /* variables */
      :root {
        /* fonts */
        --sans: 1em/1.6 system-ui, -apple-system, BlinkMacSystemFont, Segoe UI,
          Roboto, Oxygen, Ubuntu, Cantarell, Droid Sans, Helvetica Neue,
          Fira Sans, sans-serif;
        --mono: SFMono-Regular, Consolas, 'Liberation Mono', Menlo, Courier,
          'Courier New', monospace;

        /* colors */
        --c1: #080808;
        --c2: #f1f2f2;
        --c3: #2d9dff;
        --c4: #ebdbb2;
        --c5: #1d2021;
      }

      *,
      :after,
      :before {
        box-sizing: border-box;
      }

      address,
      area,
      article,
      aside,
      audio,
      blockquote,
      datalist,
      details,
      dl,
      fieldset,
      figure,
      form,
      input,
      iframe,
      img,
      meter,
      nav,
      ol,
      optgroup,
      option,
      output,
      p,
      pre,
      progress,
      ruby,
      section,
      table,
      textarea,
      ul,
      video {
        /* Margins for most elements */
        margin-bottom: 1rem;
      }

      hr {
        /* Reset the border of the <hr> separator, then set a better line */
        border: 0;
        border-bottom: 1px solid var(--c5);
        margin: 1rem auto;
      }

      body {
        margin: 0 auto;
        padding: 1em;
        font: var(--sans);
        font-weight: 400;
        line-height: 1.5;
        background: var(--c1);
        color: var(--c2);
        max-width: 40em;
        display: flex;
        flex-direction: column;
        height: 100vh;
      }

      main {
        flex: 1;
      }

      img, video {
        height: auto;
        max-width: 100%;
      }

      a {
        color: var(--c3);
        text-decoration: none;
      }

      a:hover {
        text-decoration: underline;
      }

      pre {
        font: 1em/1.6 var(--mono);
        background: var(--c5);
        color: var(--c4);
        padding: 1em;
        overflow: auto;
      }

      code {
        font: 1em/1.6 var(--mono);
        color: var(--c4);
      }

      blockquote {
        border-left: 5px solid var(--c5);
        color: var(--c4);
        padding: 1em 1.5em;
        margin: 0;
      }

      /* Headlines */
      h1,
      h2,
      h3,
      h4,
      h5,
      h6 {
        line-height: 1;
        padding-top: 0.875rem;
      }

      h1,
      h2,
      h3 {
        padding-bottom: 2px;
        margin-bottom: 8px;
      }

      h4,
      h5,
      h6 {
        margin-bottom: 0.3rem;
      }

      h1 {
        font-size: 2.25rem;
      }

      h2 {
        font-size: 1.85rem;
      }

      h3 {
        font-size: 1.55rem;
      }

      h4 {
        font-size: 1.25rem;
      }

      h5 {
        font-size: 1rem;
      }

      h6 {
        font-size: 0.875rem;
      }

      ol,
      ul {
        /* Replace the browser default padding */
        padding-left: 2rem;
      }

      li {
        margin-top: 0.4rem;
      }

      ul ul,
      ol ul,
      ul ol,
      ol ol {
        margin-bottom: 0;
      }

      footer {
        padding-top: 1.5em;
        padding-bottom: 1em;
      }

      .site-title a {
        color: var(--c2);
        font-weight: bold;
      }

      .nav {
        margin-bottom: 1em;
      }

      .nav ul {
        display: flex;
        padding: 0;
        display: flex;
        flex-wrap: wrap;
      }

      .nav ul li {
        list-style-type: none;
        margin-bottom: 0.3em;
      }

      .nav ul li:not(:last-child) {
        margin-right: 0.8em;
      }

      .theme-toggle a {
        color: var(--c2);
        background-color: var(--c5);
        padding: 0.25em 0.5em;
        border-radius: 99999999px;
      }

      .theme-toggle > a:hover {
        text-decoration: none;
      }
    
    </style>
    <!-- This icon is licensed under the Mozilla Public License 2.0 (available at: https://www.mozilla.org/en-US/MPL/2.0/).
    The original icon can be found here: https://dxr.mozilla.org/mozilla-central/source/browser/themes/shared/reader/readerMode.svg -->
    <link rel="shortcut icon" href="data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjRweCIgaGVpZ2h0PSI2NHB4IiB2ZXJzaW9uPSIxLjEiI
    HZpZXdCb3g9IjAgMCA2NCA2NCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGcgZmlsbD0iI2ZmZiI+CjxwYXRoIGQ9Im01MiAwaC00
    MGMtNC40MiAwLTggMy41OC04IDh2NDhjMCA0LjQyIDMuNTggOCA4IDhoNDBjNC40MiAwIDgtMy41OCA4LTh2LTQ4YzAtNC40Mi0zLjU4LTgtOC04em0wIDU
    yYzAgMi4yMS0xLjc5IDQtNCA0aC0zMmMtMi4yMSAwLTQtMS43OS00LTR2LTQwYzAtMi4yMSAxLjc5LTQgNC00aDMyYzIuMjEgMCA0IDEuNzkgNCA0em0tMT
    AtMzZoLTIwYy0xLjExIDAtMiAwLjg5NS0yIDJzMC44OTUgMiAyIDJoMjBjMS4xMSAwIDItMC44OTUgMi0ycy0wLjg5NS0yLTItMnptMCA4aC0yMGMtMS4xM
    SAwLTIgMC44OTUtMiAyczAuODk1IDIgMiAyaDIwYzEuMTEgMCAyLTAuODk1IDItMnMtMC44OTUtMi0yLTJ6bTAgOGgtMjBjLTEuMTEgMC0yIDAuODk1LTIg
    MnMwLjg5NSAyIDIgMmgyMGMxLjExIDAgMi0wLjg5NSAyLTJzLTAuODk1LTItMi0yem0tMTIgOGgtOGMtMS4xMSAwLTIgMC44OTUtMiAyczAuODk1IDIgMiA
    yaDhjMS4xMSAwIDItMC44OTUgMi0ycy0wLjg5NS0yLTItMnoiIGZpbGw9IiNmZmYiLz4KPC9nPgo8L3N2Zz4K"/>
</head>
<body class="qute-readability">
    <h1 class="reader-title">%s</h1>
    <div>From <a class="reader-title" href="%s">%s</a></div>
    <hr>
    %s
</body>
</html>
`;
const scriptsDir = path.join(process.env.QUTE_DATA_DIR, 'userscripts');
const tmpFile = path.join(scriptsDir, '/readability.html');

if (!fs.existsSync(scriptsDir)) {
    fs.mkdirSync(scriptsDir);
}

let getDOM, domOpts, target;
// When hinting, use the selected hint instead of the current page
if (process.env.QUTE_MODE === 'hints') {
    getDOM = JSDOM.fromURL;
    target = process.env.QUTE_URL;
}
else {
    getDOM = JSDOM.fromFile;
    domOpts = {url: process.env.QUTE_URL, contentType: "text/html; charset=utf-8"};
    target = process.env.QUTE_HTML;
}

getDOM(target, domOpts).then(dom => {
    let reader = new Readability(dom.window.document);
    let article = reader.parse();
    let subtitle = (article.siteName == null) ? new URL(process.env.QUTE_URL).hostname : article.siteName;
    let content = util.format(HEADER, article.title, article.title, process.env.QUTE_URL, subtitle, article.content);

    fs.writeFile(tmpFile, content, (err) => {
        if (err) {
            qute.messageError([`"${err}"`])
            return 1;
        }
        // Success
        qute.open(['-t', '-r', tmpFile]);
    })
});
