log-file: /tmp/efm.log
log-level: 3

tools:
  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck --format=gcc --external-sources -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  sh-shfmt: &sh-shfmt
    format-command: 'shfmt -ci -s -bn -i 2'
    format-stdin: true

  prettier-d: &prettier_d
    format-command: 'prettierd ${INPUT}'
    format-stdin: true
    root-markers:
      - '.prettierrc'
      - '.prettierrc.json'

  lua-stylua-format: &lua-stylua-format
    format-command: 'stylua -'
    format-stdin: true
    root-markers:
      - 'stylua.toml'

  luacheck: &luacheck
    lint-command: 'luacheck --globals vim --filename ${INPUT} --formatter plain -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  phpcs: &phpcs
    lint-command: './vendor/bin/phpcs --no-colors --report=emacs -q -'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - '%.%#:%l:%c: %trror - %m'
      - '%.%#:%l:%c: %tarning - %m'
    root-markers:
      - 'composer.json'

  phpcbf: &phpcbf
    format-command: './vendor/bin/phpcbf -'
    format-stdin: true
    root-markers:
      - 'composer.json'

languages:
  sh:
    - <<: *sh-shellcheck
    - <<: *sh-shfmt

  zsh:
    - <<: *sh-shellcheck
    - <<: *sh-shfmt

  bash:
    - <<: *sh-shellcheck
    - <<: *sh-shfmt

  javascript:
    - <<: *prettier_d

  php:
    - <<: *phpcs
    - <<: *phpcbf

  javascriptreact:
    - <<: *prettier_d

  typescript:
    - <<: *prettier_d

  typescriptreact:
    - <<: *prettier_d

  graphql:
    - <<: *prettier_d

  html:
    - <<: *prettier_d

  css:
    - <<: *prettier_d

  svg:
    - <<: *prettier_d

  scss:
    - <<: *prettier_d

  json:
    - <<: *prettier_d

  jsonc:
    - <<: *prettier_d

  lua:
    - <<: *lua-stylua-format
    # - <<: *luacheck
