#!/bin/sh

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx='startx $XINITRC'

# utils
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -vI'
alias mkdir='mkdir -pv'
alias sudo='sudo -v; sudo '
alias bc='bc -ql'
alias cls='clear'
alias fork='setsid -f'
alias mine='sudo chown -R $(whoami):$(whoami)'
alias ls='ls --color=auto -a'
alias ll='ls --color=auto -l -a -p -c -h'
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ip="ip -color=auto"
alias wget='wget --hsts-file=$XDG_CACHE_HOME/wget-hsts'

# apps
alias v='nvim'
alias sv='sudo -E nvim'
alias yt='youtube-dl'
alias open='xdg-open'
alias nnn='nnn -c'
alias pf='pfetch'
alias mbsync='mbsync -c $MBSYNCRC'
alias abook='abook --config $ABOOK_CONFIG --datafile $ABOOK_ADDRESS_BOOK'
alias unvim='$XDG_CONFIG_HOME/nvim/scripts/setup'
alias reload='source $ZDOTDIR/.zshrc'
alias dnd='dragon-drag-and-drop'

# systemctl
alias s='sudo systemctl'
alias ss='sudo systemctl status'
alias sr='sudo systemctl restart'
alias sst='sudo systemctl start'
alias ssp='sudo systemctl stop'
alias sds='sudo systemctl disable'
alias sen='sudo systemctl enable'
alias ssu='systemctl --user'
alias ssus='systemctl --user status'
alias ssur='systemctl --user restart'
alias ssust='systemctl --user start'
alias ssusp='systemctl --user stop'
alias ssud='systemctl --user disable'
alias ssuen='systemctl --user enable'

# configs
alias cfz='$EDITOR $XDG_CONFIG_HOME/zsh/.zshrc'
alias cfv='$EDITOR $XDG_CONFIG_HOME/nvim/init.lua'
alias cft='$EDITOR $XDG_CONFIG_HOME/tmux/tmux.conf'
alias cfp='$EDITOR $XDG_CONFIG_HOME/picom/picom.conf'
alias cfk='$EDITOR $XDG_CONFIG_HOME/sxhkd/sxhkdrc'
alias cfq='$EDITOR $XDG_CONFIG_HOME/qutebrowser/config.py'
alias cfs='$EDITOR $XDG_CONFIG_HOME/shell/profile'
alias cfx='$EDITOR $XDG_CONFIG_HOME/x11/xinitrc'

# youtube-dl
alias yta-best='youtube-dl --extract-audio --audio-format best '
alias yta-mp3='youtube-dl --extract-audio --audio-format mp3 '
alias ytb='youtube-dl -f bestvideo+bestaudio '
alias drm-dl='youtube-dl --external-downloader axel --no-warnings --allow-unplayable-formats --no-check-certificate --concurrent-fragments 10'

# paru
alias p='paru'
alias pa='paru -S'
alias pr='paru -Rns'

# navigation
alias ..='cd ..'
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../..'
alias .5='cd ../../../..'
alias .6='cd ../../../../..'
alias .6='cd ../../../../../..'
alias .7='cd ../../../../../../..'
alias .8='cd ../../../../../../../..'
alias .9='cd ../../../../../../../../..'
alias .10='cd ../../../../../../../../../..'

# yarn
alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'
alias y='yarn'
alias yw='yarn  workspace'
alias yst='yarn start'
alias yd='yarn dev'
alias ya='yarn add'
alias yr='yarn remove'
alias yad='yarn add -D'

# npm
alias n='npm'
alias ni='npm install'
alias na='npm install'
alias nad='npm install --dev'
alias nr='npm uninstall'
alias nst='npm run start'
alias nd='npm run dev'

# tmux
alias t='tmux'
alias ta='t a -t'
alias tls='t ls'
alias tn='t new -t'
alias tk='t kill-session -t'

# docker
alias d='docker'
alias ds='docker ps'
alias dexec='docker exec -it'
alias dc='docker compose'
alias dcup='docker compose up -d'
alias dcd='docker compose stop'

# kubernetes
alias k='kubectl'
alias kps='kubectl get pods'
alias kds='kubectl get deployments'
alias kss='kubectl get services'
alias ka='kubectl apply -f'
alias kd='kubectl delete pod'

# git
alias g='git'
alias gs='git status'
alias ga='git add'
alias gc='git commit -v'
alias gpl='git pull'
alias gf='git fetch'
alias gm='git merge'
alias gco='git checkout'
alias gcb='git checkout -b'

gpu() {
  if [ -z "$1" ]; then
    git push -u origin HEAD
  else
    git push "$@"
  fi
}

compdef _git gpu=git-push

alias gcl='git clone'
alias gz='git undo'
alias gl='git l'
alias gsa='git submodule add'
alias gb='git branch'
alias gbd='git branch -D'
