#!/bin/zsh

source "$HOME/.config/shell/private-envs"

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_VIDEOS_DIR="$HOME/vids"
export XDG_PICTURES_DIR="$HOME/pics"
export XDG_DOWNLOAD_DIR="$HOME/dls"
export XCURSOR_PATH="$XCURSOR_PATH:/usr/share/icons:${XDG_DATA_HOME}/icons"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# android/java
export ANDROID_HOME="$XDG_CONFIG_HOME/android/Sdk"
export ANDROID_AVD_HOME="$XDG_CONFIG_HOME/android/avd"
export GRADLE_USER_HOME="$XDG_DATA_HOME/gradle"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java

# theme (dynamic)
export QT_QPA_PLATFORMTHEME=qt6ct
export ADW_DISABLE_PORTAL=1

# pass
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"

# tmux
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"

# rust
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"

# go
export GOPATH="$XDG_DATA_HOME/go"

# Kodi
export KODI_DATA="$XDG_DATA_HOME"/kodi

# node
export VOLTA_HOME="$XDG_DATA_HOME/volta"
export NODE_REPL_HISTORY="$XDG_CACHE_HOME/node_repl_history"
export PM2_HOME="$XDG_DATA_HOME/pm2"

# npm
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"

# docker
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"

# abook
export ABOOK_CONFIG="$XDG_CONFIG_HOME/abook/abookrc"
export ABOOK_ADDRESS_BOOK="$XDG_DATA_HOME/abook/addressbook"

# zoom
export SSB_HOME="$XDG_DATA_HOME/zoom"

# wget
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"

# gnupg
export GNUPGHOME="$XDG_DATA_HOME/gnupg"

# mbsync
export MBSYNCRC="$XDG_CONFIG_HOME/isync/mbsyncrc"

# python
export PYTHONHISTFILE="$XDG_CACHE_HOME/python_history"
export PYTHONSTARTUP=~/.config/python/pythonrc

# vscode
export VSCODE_PORTABLE="$XDG_DATA_HOME/vscode"

# redis
export REDISCLI_HISTFILE="$XDG_CACHE_HOME/redis/rediscli_history"
export REDISCLI_RCFILE="$XDG_CONFIG_HOME/redis/redisclirc"

# deno
export DENO_INSTALL="$XDG_DATA_HOME/deno"

# ruby
export GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem"

# php
export PHP_CS_FIXER_IGNORE_ENV=1
export PHPENV_ROOT="$HOME/.phpenv"

# ripgrep
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME/ripgreprc"

# lynx
export LYNX_CFG="$XDG_CONFIG_HOME/lynx/lynx.cfg"
export LYNX_LSS="$XDG_CONFIG_HOME/lynx/lynx.lss"

# wine
export WINEPREFIX="$XDG_DATA_HOME"/wineprefixes/default

# nnn config
export GUI=1
export NNN_OPENER="$XDG_CONFIG_HOME/nnn/plugins/nuke"
export NNN_FCOLORS='c1e2272e006033f7c6d6abc4'
export NNN_FIFO='/tmp/nnn.fifo'
export NNN_PLUG="z:autojump;p:preview-tui;u:imgur;d:dragdrop"
export NNN_TRASH=1
export NNN_TERMINAL="foot -e"
export NNN_ICONLOOKUP=1

# pfetch
export PF_INFO="ascii os wm host pkgs shell editor"

# MongoHud
export MANGOHUD_CONFIGFILE="$XDG_CONFIG_HOME/MangoHud/MangoHud.conf"

# Wakatime
export WAKATIME_HOME="$XDG_CONFIG_HOME/wakatime"

# lazygit
export LG_CONFIG_FILE="$XDG_CONFIG_HOME/lazygit/config.yml,$XDG_CONFIG_HOME/ricing/lazygit-theme.yml"

# other
export PKG_CACHE_PATH="$XDG_DATA_HOME/pkg-cache"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
export RANDFILE="$XDG_CACHE_HOME/rnd"
export HISTFILE="$XDG_DATA_HOME/bash/history"
export MAIL="$XDG_DATA_HOME/mail"
export ASDF_DATA_DIR="$XDG_DATA_HOME/asdf"

# Default programs:
export EDITOR="$XDG_DATA_HOME/mise/installs/neovim/nightly/bin/nvim"
export VISUAL="$XDG_DATA_HOME/mise/installs/neovim/nightly/bin/nvim"
export TERMINAL="foot"
export BROWSER="qutebrowser"
export READER="zathura"
export WM='niri'
export VIDEO="mpv"
export IMAGE="sxiv"
export COLORTERM="truecolor"
export FILE_MANAGER='thunar'
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANROFFOPT="-c"

# Fix for Java apps
export _JAVA_AWT_WM_NONREPARENTING=1

# path
PATH="/usr/local/bin:$PATH"
PATH="$HOME/.local/bin:$PATH"
PATH="$HOME/.local/bin/Bento4/bin:$PATH"
PATH="$VOLTA_HOME/bin:$PATH"
PATH="$CARGO_HOME/bin:$PATH"
PATH="$DENO_INSTALL/bin:$PATH"
PATH="$GOPATH/bin:$PATH"
PATH="$GEM_HOME/bin:$PATH"
PATH="$ANDROID_HOME/emulator:$PATH"
PATH="$ANDROID_HOME/tools:$PATH"
PATH="$ANDROID_HOME/tools/bin:$PATH"
PATH="$ANDROID_HOME/platform-tools:$PATH"
PATH="$HOME/.php-school/bin:$PATH"
PATH="$HOME/.config/composer/vendor/bin:$PATH"
PATH="$XDG_CONFIG_HOME/tizen-studio/tools:$PATH"
PATH="$XDG_CONFIG_HOME/tizen-studio/tools/ide/bin:$PATH"
PATH="$ASDF_DATA_DIR/shims:$PATH"
PATH="$HOME/.local/share/bob/nvim-bin:$PATH"

export PATH

if [ "$(tty)" = "/dev/tty1" ] && [ -z "$WAYLAND_DISPLAY" ] && [ -z "$DISPLAY" ]; then
  export XDG_SESSION_TYPE=wayland
  export XDG_CURRENT_DESKTOP=niri
  export XDG_SESSION_DESKTOP=niri

  if command -v systemctl >/dev/null 2>&1; then
    systemctl --user import-environment \
      XDG_SESSION_TYPE XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP WAYLAND_DISPLAY
  fi

  if command -v dbus-update-activation-environment >/dev/null 2>&1; then
    dbus-update-activation-environment --systemd \
      XDG_SESSION_TYPE XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP WAYLAND_DISPLAY
  fi

  exec niri-session
fi
