#!/bin/zsh

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XCURSOR_PATH=/usr/share/icons:${XDG_DATA_HOME}/icons

# X11
export XINITRC="/home/ashraf/.config/x11/xinitrc"
# export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZSH_CACHE_DIR="$XDG_CACHE_HOME/zsh"

# android/java
# export ANDROID_HOME="$XDG_CONFIG_HOME/android"
# export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
export ANDROID_SDK_ROOT="$XDG_CONFIG_HOME/android/Sdk"
export GRADLE_USER_HOME="$XDG_DATA_HOME/gradle"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java

# theme
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export QT_QPA_PLATFORMTHEME="gtk2"

# pass
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"

# tmux
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"

# rust
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"

# go
export GOPATH="$XDG_DATA_HOME/go"

# Kodi
export KODI_DATA="$XDG_DATA_HOME"/kodi

# node
export NODE_REPL_HISTORY="$XDG_CACHE_HOME/node_repl_history"
export PM2_HOME="$XDG_DATA_HOME/pm2"
export VOLTA_HOME="$XDG_DATA_HOME/volta"

# npm
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"

# abook
export ABOOK_CONFIG="$XDG_CONFIG_HOME/abook/abookrc"
export ABOOK_ADDRESS_BOOK="$XDG_DATA_HOME/abook/addressbook"

# zoom
export SSB_HOME="$XDG_DATA_HOME/zoom"

# wget
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"

# gnupg
export GNUPGHOME="$XDG_DATA_HOME/gnupg"

# mbsync
export MBSYNCRC="$XDG_CONFIG_HOME/isync/mbsyncrc"

# python
export PYTHONHISTFILE="$XDG_CACHE_HOME/python_history"
export PYTHONSTARTUP=~/.config/python/pythonrc

# vscode
export VSCODE_PORTABLE="$XDG_DATA_HOME/vscode"

# redis
export REDISCLI_HISTFILE="$XDG_CACHE_HOME/redis/rediscli_history"
export REDISCLI_RCFILE="$XDG_CONFIG_HOME/redis/redisclirc"

# deno
export DENO_INSTALL="$XDG_DATA_HOME/deno"

# ruby
export RUBY_BIN="/opt/homebrew/opt/ruby/bin/ruby"
export GEM_HOME="$("$RUBY_BIN" -e 'puts Gem.user_dir')"
export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem"

# ripgrep
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME/ripgreprc"

# lynx
export LYNX_CFG="$XDG_CONFIG_HOME/lynx/lynx.cfg"
export LYNX_LSS="$XDG_CONFIG_HOME/lynx/lynx.lss"

# wine
export WINEPREFIX="$XDG_DATA_HOME"/wineprefixes/default

# nnn config
export GUI=1
export NNN_OPENER="$XDG_CONFIG_HOME/nnn/plugins/nuke"	
export NNN_FCOLORS='c1e2272e006033f7c6d6abc4'
export NNN_FIFO='/tmp/nnn.fifo'
export NNN_PLUG="z:autojump;p:preview-tabbed;u:imgur;d:dragdrop"
export NNN_TRASH=1

# fzf config
export FZF_DEFAULT_COMMAND="rg --files --hidden --glob '!.git'"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# pfetch
export PF_INFO="ascii os wm host pkgs shell editor"

# MongoHud
export MANGOHUD_CONFIGFILE="$XDG_CONFIG_HOME/MangoHud/MangoHud.conf"

# other
export PKG_CACHE_PATH="$XDG_DATA_HOME/pkg-cache"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
export RANDFILE="$XDG_CACHE_HOME/rnd"
export HISTFILE="$XDG_DATA_HOME/bash/history"
export MAIL="$XDG_DATA_HOME/mail"
export LS_COLORS=${LS_COLORS:-'di=34:ln=35:so=32:pi=33:ex=31:bd=36;01:cd=33;01:su=31;40;07:sg=36;40;07:tw=32;40;07:ow=33;40;07:'}

# Default programs:
export EDITOR="nvim"
export VISUAL="nvim"
export TERMINAL="st"
export BROWSER="qutebrowser"
export READER="zathura"
export WM='dwm'
export VIDEO="mpv"
export IMAGE="sxiv"
export COLORTERM="truecolor"
export MANPAGER="sh -c 'col -bx | bat -l man -p --paging always'"

# Fix for Java apps
export _JAVA_AWT_WM_NONREPARENTING=1

# path
typeset -U PATH path

path=(
  "$HOME/.local/bin"
  "/usr/local/bin"
  "/usr/local/sbin"
  "/opt/homebrew/bin"
   "/opt/homebrew/opt/cocoapods/bin"
   "/opt/homebrew/opt/ruby/bin"
  "$HOME/.local/bin/Bento4/bin/"
  "$VOLTA_HOME/bin"
  "$CARGO_HOME/bin"
  "$DENO_INSTALL/bin"
  "$GOPATH/bin"
  "$GEM_HOME/bin"
  "$ANDROID_SDK_ROOT/emulator"
  "$ANDROID_SDK_ROOT/platform-tools"
  "$path[@]"
)

export PATH
