#!/bin/sh
while read -r file; do
  case "$1" in
    "w") feh --bg-fil "$file" & ;;
    "r") convert -rotate 90 "$file" "$file" ;;
    "R") convert -rotate -90 "$file" "$file" ;;
    "f") convert -flop "$file" "$file" ;;
    "d")
      [ "$(printf 'No\nYes' | dmenu -r -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted."
      ;;
  esac
done
