# Bindings for normal mode
config.bind('V', 'spawn mpv --ytdl-format="[height<=?720]" {url}')
config.bind(',v', 'hint links spawn mpv --ytdl-format="[height<=?720]" {hint-url}')
config.bind('M', 'spawn mpv --ytdl-format="[height<=?480]" {url}')
config.bind(',m', 'hint links spawn mpv --ytdl-format="[height<=?480]" {hint-url}')
config.bind(',p', 'spawn --userscript qute-bitwarden --auto-lock 60480000')
config.bind(',i', 'hint images run open {hint-url}')
config.bind(',r', 'config-source')
config.bind("<", "tab-move -")
config.bind(">", "tab-move +")
config.bind('<alt-left>', 'back')
config.bind('<alt-right>', 'forward')
config.bind("<Ctrl+Shift+Tab>", "tab-prev")
config.bind("<Ctrl+Tab>", "tab-next")
config.unbind('<Ctrl+h>', "normal")
config.bind("<Ctrl+h>", "history")

config.bind('<Ctrl-h>', 'fake-key <Backspace>', 'insert')
config.bind('<Ctrl-a>', 'fake-key <Home>', 'insert')
config.bind('<Ctrl-e>', 'fake-key <End>', 'insert')
config.bind('<Ctrl-b>', 'fake-key <Left>', 'insert')
config.bind('<Mod1-b>', 'fake-key <Ctrl-Left>', 'insert')
config.bind('<Ctrl-f>', 'fake-key <Right>', 'insert')
config.bind('<Mod1-f>', 'fake-key <Ctrl-Right>', 'insert')
config.bind('<Ctrl-p>', 'fake-key <Up>', 'insert')
config.bind('<Ctrl-n>', 'fake-key <Down>', 'insert')
config.bind('<Mod1-d>', 'fake-key <Ctrl-Delete>', 'insert')
config.bind('<Ctrl-d>', 'fake-key <Delete>', 'insert')
config.bind('<Ctrl-w>', 'fake-key <Ctrl-Backspace>', 'insert')
config.bind('<Ctrl-u>', 'fake-key <Shift-Home><Delete>', 'insert')
config.bind('<Ctrl-k>', 'fake-key <Shift-End><Delete>', 'insert')
config.bind('<Ctrl-e>', 'open-editor', 'insert')
