#! /bin/sh
bspc rule -r "*"

# script to simulate i3 fullscreen behaviour
cleanfullscreen & 
# launch polybar
$XDG_CONFIG_HOME/polybar/launch.sh & 
# launch sxhkd hot key binding
sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 

bspc config border_width            2
bspc config window_gap              15
bspc config split_ratio             0.50
bspc config top_padding 						20
bspc config bottom_padding 					20
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config center_pseudo_tiled     true
bspc config persistent_monitors     true
bspc config focus_follows_pointer   true

# bspc config active_border_color	"#2E3440"
# bspc config focused_border_color "#5E81AC"

bspc config active_border_color	"#eaeaea"
bspc config focused_border_color "#70c0ba"

###---Rules---###
bspc rule -a mpv state=fullscreen
bspc rule -a mpv desktop='^6'
bspc rule -a discord desktop='^8'
bspc rule -a '*:spotify'  desktop='^9'
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a Android_Studio state=tiled
bspc rule -a "*:Picture in picture" state=floating
bspc rule -a '*:pavucontrol' state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Glava manage=off
