#! /bin/sh
bspc rule -r "*"

# change the default cross cursor to left pointer cursor
xsetroot -cursor_name left_ptr &
# script to simulate i3 fullscreen behaviour
cleanfullscreen & 
# hide mouse cursor while not using it
unclutter --timeout 2  &
# set both english and arabic layout
setxkbmap -layout us,ar &
# network manager
nm-applet &
# set random wallpaper
feh --bg-fill --randomize ~/wallpapers/* &
# source Xresources file
xrdb ~/.Xresources &
# start dunst notification server
dunst &
# launch polybar
/home/ashraf/.config/polybar/launch.sh & 
# launch picom compositor 
picom --experimental-backend &
# launch sxhkd hot key binding
sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 

bspc config border_width            0
bspc config window_gap              0
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config center_pseudo_tiled     true
bspc config persistent_monitors     true
bspc config focus_follows_pointer   true
wmname LG3D

bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#b8bb26"

###---Rules---###
bspc rule -a mpv state=fullscreen
bspc rule -a discord desktop='^8'
bspc rule -a '*:spotify'  desktop='^9'
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a Android_Studio state=tiled
bspc rule -a '*:pavucontrol' state=floating
bspc rule -a Screenkey manage=off





