#!/bin/sh

while read -r file; do
  case "$1" in
  "w") setbg "$file" & ;;
  "r") magick "$file" -rotate 90 "$file" ;;
  "R") magick "$file" -rotate -90 "$file" ;;
  "f") magick "$file" -flop "$file" ;;
  "c")
    xclip -selection clipboard -t "$(file --brief --mime-type "$file")" -i "$file" &&
      dunstify -i "$(readlink -f "$file")" "\"$(basename "$file")\" copied to clipboard" &
    ;;
  "y")
    printf "%s" "$file" | tr -d '\n' | xclip -selection clipboard &&
      notify-send "$file copied to clipboard" &
    ;;
  "Y")
    readlink -f "$file" | tr -d '\n' | xclip -selection clipboard &&
      notify-send "$(readlink -f "$file") copied to clipboard" &
    ;;
  "d")
    trash-put "$file"
    ;;

  "D")
    dragon-drop -x "$file"
    ;;

  "I")
    imgur.sh "$file" 2>/dev/null | head -n 1 | xclip -sel c -r &&
      notify-send "🖼 image uploaded"
    ;;

  "e")
    pinta "$file" &
    ;;
  esac
done
