#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config layout bsp

yabai -m config window_placement             second_child

yabai -m config top_padding    11
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     10

yabai -m config split_ratio 0.5

yabai -m config window_border                on
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555

